name: coffee_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  like_button: ^2.0.5
  cached_network_image: ^3.2.3
  lottie: ^2.5.0
  flutter_rating_stars: ^1.0.3+4
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.1.0
  connectivity_plus: ^5.0.1
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
